[package]
name = "qvs-format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
qvs-core = { path = "../qvs-core" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
sha1.workspace = true
hex.workspace = true
lru.workspace = true
async-trait.workspace = true
dirs.workspace = true

[dev-dependencies]
tempfile = "3"
