//! Application icon support.
//!
//! Loads the embedded `qvod.ico` at runtime and provides RGBA pixel data
//! for both the window / taskbar icon ([`egui::IconData`]) and the in-GUI
//! title-bar / about-dialog icon ([`egui::ColorImage`] / texture).
//!
//! The ICO is generated by `scripts/generate-icon.py` which strips the white
//! background at the source, so the embedded PNGs already carry correct
//! transparency.  We do **not** apply any post-hoc alpha cleaning — the
//! native alpha from the ICO file is preserved as-is.

use std::sync::OnceLock;

use eframe::egui::{self, ColorImage};

/// Embedded ICO file bytes (compiled into the binary via `include_bytes!`).
const ICO_BYTES: &[u8] = include_bytes!("../assets/qvod.ico");

// ---------------------------------------------------------------------------
// Cached decoded images (two sizes)
// ---------------------------------------------------------------------------

static DECODED_LARGE: OnceLock<DecodedIcon> = OnceLock::new();
static DECODED_SMALL: OnceLock<DecodedIcon> = OnceLock::new();

struct DecodedIcon {
    rgba: Vec<u8>,
    width: u32,
    height: u32,
}

/// 64×64 — for the window / taskbar icon (ViewportBuilder::with_icon).
fn decode_large() -> &'static DecodedIcon {
    DECODED_LARGE.get_or_init(|| {
        let img = image::load_from_memory(ICO_BYTES).expect("Failed to decode qvod.ico");
        let img = img.resize_exact(64, 64, image::imageops::FilterType::Lanczos3);
        let rgba = img.to_rgba8();
        let (width, height) = rgba.dimensions();
        DecodedIcon {
            rgba: rgba.to_vec(),
            width,
            height,
        }
    })
}

/// 16×16 (native first ICO entry) — for the title-bar / in-GUI icon.
fn decode_small() -> &'static DecodedIcon {
    DECODED_SMALL.get_or_init(|| {
        let img = image::load_from_memory(ICO_BYTES).expect("Failed to decode qvod.ico");
        // Keep the original size from the first ICO entry (16×16).
        let rgba = img.to_rgba8();
        let (width, height) = rgba.dimensions();
        DecodedIcon {
            rgba: rgba.to_vec(),
            width,
            height,
        }
    })
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Returns an [`egui::IconData`] suitable for
/// [`egui::ViewportBuilder::with_icon`] (64×64).
pub fn icon_data() -> egui::IconData {
    let d = decode_large();
    egui::IconData {
        rgba: d.rgba.clone(),
        width: d.width,
        height: d.height,
    }
}

/// Returns the decoded icon as a [`ColorImage`] (64×64).
pub fn color_image() -> &'static ColorImage {
    static IMG: OnceLock<ColorImage> = OnceLock::new();
    IMG.get_or_init(|| {
        let d = decode_large();
        ColorImage::from_rgba_unmultiplied([d.width as usize, d.height as usize], &d.rgba)
    })
}

/// Returns the icon at its native 16×16 size.
pub fn color_image_small() -> &'static ColorImage {
    static IMG: OnceLock<ColorImage> = OnceLock::new();
    IMG.get_or_init(|| {
        let d = decode_small();
        ColorImage::from_rgba_unmultiplied([d.width as usize, d.height as usize], &d.rgba)
    })
}
